version: "3.4"

services:
  backend:
    container_name: backend
    restart: always
    command: node server.js
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
