version: "3.4"

services:
  backendwc:
    image: backendwc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - 1000:1000
    volumes:
      - data:/data/db

volumes:
  data:
